apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sre-cluster
servers: 1
agents: 1 # An extra worker node to simulate a distributed environment
image: rancher/k3s:v1.31.5-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
